"""Erie County 2024 general (XLSX, per-sheet SOVC with a two-level hierarchy).

Header is row 0: office title in col0, then 'Name  <LongParty>' cells
(Democratic/Republican/Conservative/LaRouche/Working Families/Restore Freedom),
plus Write-In / Blank / Void / Scattering / TOTAL control columns.  Precinct
rows are matched by a regex (town/ward code + ED number); section headers,
sub-totals and recap rows fail it and are skipped.  The 'Erie County Total' row
is the anchor cross-check.
"""
from ..model import CountyConfig

_SHEETS = [
    ("U.S. President", "President", ""),
    ("U.S. Senator", "U.S. Senate", ""),
    ("Congressional Rep. (23rd Dist.)", "U.S. House", "23"),
    ("Congressional Rep. (26th Dist.)", "U.S. House", "26"),
    ("State Senator (60th Dist.)", "State Senate", "60"),
    ("State Senator (61st Dist.)", "State Senate", "61"),
    ("State Senator (63rd Dist.)", "State Senate", "63"),
    ("Mem. of Assembly (139th Dist.)", "State Assembly", "139"),
    ("Mem. of Assembly (140th Dist.)", "State Assembly", "140"),
    ("Mem. of Assembly (141st Dist.)", "State Assembly", "141"),
    ("Mem. of Assembly (142nd Dist.)", "State Assembly", "142"),
    ("Mem. of Assembly (143rd Dist.)", "State Assembly", "143"),
    ("Mem. of Assembly (144th Dist.)", "State Assembly", "144"),
    ("Mem. of Assembly (145th Dist.)", "State Assembly", "145"),
    ("Mem. of Assembly (146th Dist.)", "State Assembly", "146"),
    ("Mem. of Assembly (147th Dist.)", "State Assembly", "147"),
    ("Mem. of Assembly (149th Dist.)", "State Assembly", "149"),
    ("Mem. of Assembly (150th Dist.)", "State Assembly", "150"),
]
_ORDER = [(o, d) for _, o, d in _SHEETS]

CAND = {
    ("President", "", "DEM"): "Kamala D. Harris",
    ("President", "", "WOR"): "Kamala D. Harris",
    ("President", "", "REP"): "Donald J. Trump",
    ("President", "", "CON"): "Donald J. Trump",
    ("U.S. Senate", "", "DEM"): "Kirsten E. Gillibrand",
    ("U.S. Senate", "", "WOR"): "Kirsten E. Gillibrand",
    ("U.S. Senate", "", "REP"): "Michael D. Sapraicone",
    ("U.S. Senate", "", "CON"): "Michael D. Sapraicone",
    ("U.S. Senate", "", "LAR"): "Diane Sare",
    ("U.S. House", "23", "DEM"): "Thomas A. Carle",
    ("U.S. House", "23", "REP"): "Nicholas A. Langworthy",
    ("U.S. House", "23", "CON"): "Nicholas A. Langworthy",
    ("U.S. House", "26", "DEM"): "Timothy M. Kennedy",
    ("U.S. House", "26", "WOR"): "Timothy M. Kennedy",
    ("U.S. House", "26", "REP"): "Anthony G. Marecki",
    ("U.S. House", "26", "CON"): "Anthony G. Marecki",
    ("State Senate", "60", "REP"): "Patrick M. Gallivan",
    ("State Senate", "60", "CON"): "Patrick M. Gallivan",
    ("State Senate", "61", "DEM"): "Sean M. Ryan",
    ("State Senate", "61", "WOR"): "Sean M. Ryan",
    ("State Senate", "61", "REP"): "Christine M. Czarnik",
    ("State Senate", "61", "CON"): "Christine M. Czarnik",
    ("State Senate", "63", "DEM"): "April Baskin",
    ("State Senate", "63", "WOR"): "April Baskin",
    ("State Senate", "63", "REP"): "John P. Moretti Jr.",
    ("State Senate", "63", "CON"): "John P. Moretti Jr.",
    ("State Assembly", "139", "REP"): "Stephen M. Hawley",
    ("State Assembly", "139", "CON"): "Stephen M. Hawley",
    ("State Assembly", "140", "DEM"): "William C. Conrad III",
    ("State Assembly", "140", "WOR"): "William C. Conrad III",
    ("State Assembly", "141", "DEM"): "Crystal D. Peoples",
    ("State Assembly", "142", "DEM"): "Patrick B. Burke",
    ("State Assembly", "142", "REP"): "Marc D. Priore",
    ("State Assembly", "142", "CON"): "Marc D. Priore",
    ("State Assembly", "143", "DEM"): "Monica Piga Wallace",
    ("State Assembly", "143", "WOR"): "Monica Piga Wallace",
    ("State Assembly", "143", "REP"): "Patrick J. Chludzinski",
    ("State Assembly", "143", "CON"): "Patrick J. Chludzinski",
    ("State Assembly", "144", "DEM"): "Michelle M. Roman",
    ("State Assembly", "144", "WOR"): "Michelle M. Roman",
    ("State Assembly", "144", "REP"): "Paul A. Bologna",
    ("State Assembly", "144", "CON"): "Paul A. Bologna",
    ("State Assembly", "145", "DEM"): "Jeffrey Elder",
    ("State Assembly", "145", "WOR"): "Jeffrey Elder",
    ("State Assembly", "145", "REP"): "Angelo J. Morinello",
    ("State Assembly", "145", "CON"): "Angelo J. Morinello",
    ("State Assembly", "146", "DEM"): "Karen M. McMahon",
    ("State Assembly", "146", "WOR"): "Karen M. McMahon",
    ("State Assembly", "146", "REP"): "Deborah L. Kilbourn",
    ("State Assembly", "146", "CON"): "Deborah L. Kilbourn",
    ("State Assembly", "147", "DEM"): "Darci B. Cramer",
    ("State Assembly", "147", "REP"): "David J. DiPietro",
    ("State Assembly", "147", "CON"): "David J. DiPietro",
    ("State Assembly", "149", "DEM"): "Jonathan D. Rivera",
    ("State Assembly", "149", "WOR"): "Jonathan D. Rivera",
    ("State Assembly", "150", "DEM"): "Mike Bobseine",
    ("State Assembly", "150", "WOR"): "Mike Bobseine",
    ("State Assembly", "150", "RSF"): "Mike Bobseine",
    ("State Assembly", "150", "REP"): "Andrew M. Molitor",
    ("State Assembly", "150", "CON"): "Andrew M. Molitor",
}

ANCHORS = {
    ("President", "", "DEM"): 234407, ("President", "", "WOR"): 14244,
    ("President", "", "REP"): 178177, ("President", "", "CON"): 26597,
    ("President", "", "_WI"): 6501,
    ("U.S. Senate", "", "DEM"): 231473, ("U.S. Senate", "", "WOR"): 21309,
    ("U.S. Senate", "", "REP"): 158669, ("U.S. Senate", "", "CON"): 28878,
    ("U.S. Senate", "", "LAR"): 1926, ("U.S. Senate", "", "_WI"): 569,
    ("U.S. House", "23", "DEM"): 59031, ("U.S. House", "23", "REP"): 82191,
    ("U.S. House", "23", "CON"): 16331, ("U.S. House", "23", "_WI"): 112,
    ("U.S. House", "26", "DEM"): 170113, ("U.S. House", "26", "WOR"): 16498,
    ("U.S. House", "26", "REP"): 77415, ("U.S. House", "26", "CON"): 13895,
    ("U.S. House", "26", "_WI"): 383,
    ("State Senate", "60", "REP"): 109393, ("State Senate", "60", "CON"): 27499,
    ("State Senate", "60", "_WI"): 1424,
    ("State Senate", "61", "DEM"): 80274, ("State Senate", "61", "WOR"): 8146,
    ("State Senate", "61", "REP"): 46343, ("State Senate", "61", "CON"): 8323,
    ("State Senate", "61", "_WI"): 160,
    ("State Senate", "63", "DEM"): 64386, ("State Senate", "63", "WOR"): 5580,
    ("State Senate", "63", "REP"): 30043, ("State Senate", "63", "CON"): 5341,
    ("State Senate", "63", "_WI"): 180,
    ("State Assembly", "139", "REP"): 0, ("State Assembly", "139", "CON"): 0,
    ("State Assembly", "139", "_WI"): 0,
    ("State Assembly", "140", "DEM"): 30881, ("State Assembly", "140", "WOR"): 6704,
    ("State Assembly", "140", "_WI"): 326,
    ("State Assembly", "141", "DEM"): 35582, ("State Assembly", "141", "_WI"): 287,
    ("State Assembly", "142", "DEM"): 29192, ("State Assembly", "142", "REP"): 23463,
    ("State Assembly", "142", "CON"): 4912, ("State Assembly", "142", "_WI"): 83,
    ("State Assembly", "143", "DEM"): 26176, ("State Assembly", "143", "WOR"): 2032,
    ("State Assembly", "143", "REP"): 25802, ("State Assembly", "143", "CON"): 4607,
    ("State Assembly", "143", "_WI"): 64,
    ("State Assembly", "144", "DEM"): 12344, ("State Assembly", "144", "WOR"): 783,
    ("State Assembly", "144", "REP"): 17706, ("State Assembly", "144", "CON"): 3311,
    ("State Assembly", "144", "_WI"): 18,
    ("State Assembly", "145", "DEM"): 4308, ("State Assembly", "145", "WOR"): 379,
    ("State Assembly", "145", "REP"): 6388, ("State Assembly", "145", "CON"): 1169,
    ("State Assembly", "145", "_WI"): 4,
    ("State Assembly", "146", "DEM"): 34720, ("State Assembly", "146", "WOR"): 2650,
    ("State Assembly", "146", "REP"): 21055, ("State Assembly", "146", "CON"): 3826,
    ("State Assembly", "146", "_WI"): 60,
    ("State Assembly", "147", "DEM"): 21431, ("State Assembly", "147", "REP"): 33718,
    ("State Assembly", "147", "CON"): 7088, ("State Assembly", "147", "_WI"): 45,
    ("State Assembly", "149", "DEM"): 30507, ("State Assembly", "149", "WOR"): 7584,
    ("State Assembly", "149", "_WI"): 449,
    ("State Assembly", "150", "DEM"): 225, ("State Assembly", "150", "WOR"): 28,
    ("State Assembly", "150", "RSF"): 0, ("State Assembly", "150", "REP"): 63,
    ("State Assembly", "150", "CON"): 9, ("State Assembly", "150", "_WI"): 0,
}

CONFIG = CountyConfig(
    county="Erie",
    slug="erie",
    engine="tabular",
    source_name="Erie.xlsx",
    office_order=_ORDER,
    cand=CAND,
    anchors=ANCHORS,
    extra_parties=("RSF",),
    engine_opts={
        "header_style": "trailing_party_token",
        "sheets": _SHEETS,
        "header_row": 0,
        "precinct_regex": r"^[A-Za-z]+(?: \d+)+$",
        "total_labels": ("erie county total",),
        "writein_prefixes": ("scattering",),
        "writein_suffixes": ("write-in", "write-ins"),
        "over_prefixes": ("void",),
        "under_prefixes": ("blank",),
        "tv_labels": ("total",),
        "tv_mode": "sum_all",
    },
)
